### PR TITLE
[MRG] Switch from pep8 to flake8

### LINKED ISSUE #43: Switch pep8 references to pycodestyle
pep8 is renaming

### PR DESCRIPTION
**Pull request by mohamed-ali**
#### Reference Issues/PRs
Fixes #43

#### What does this implement/fix? Explain your changes.
This PR introduces the necessary changes to switch from using the `pep8` package to the `flake8` package.  

#### Any other comments?
Instead of switching from `pep8` to `pycodestyles` as suggested initially. We agreed to switch to `flake8` which wraps pyflakes and pycodestyle:

- pypi: https://pypi.python.org/pypi/flake8
- doc: http://flake8.pycqa.org/en/latest/

### CODE REVIEW

**Comment by mohamed-ali** [comment]
@holdenk using flake8 on the code raises a number of errors that's why travis is failing. 

```
$ flake8 --ignore=E402 sparklingml/ | wc -l 
137
```
I think it's better if I create another pull request to address these issues separately. What do you think?

**Comment by mohamed-ali** [comment]
Most of the flake8 errors (F999,F403) are due to the use of `import *`, which is generally discouraged in python development. So, if we ignore these errors, we are left with the following:

```
$ flake8 --ignore=E402,F999,F403 sparklingml/
sparklingml/__init__.py:24:1: F401 'sys' imported but unused
sparklingml/__init__.py:25:1: F401 'pyspark' imported but unused
sparklingml/startup.py:8:1: F401 'PandasUDFType' imported but unused
sparklingml/transformation_functions.py:5:1: F401 'pandas' imported but unused
sparklingml/transformation_functions.py:9:1: F401 'pandas_udf' imported but unused
sparklingml/feature/__init__.py:22:1: F401 'os' imported but unused
sparklingml/feature/__init__.py:23:1: F401 'sys' imported but unused
sparklingml/feature/__init__.py:24:1: F401 'pyspark' imported but unused
sparklingml/feature/__init__.py:25:1: F401 'resource_filename' imported but unused
```

@holdenk: Let me know if it's ok to fix these in the current PR or create a separate one for that.

**Comment by mohamed-ali** [comment]
@holdenk I changed travis to this: 
```
"flake8 --ignore=E402,F999,F403,F401 sparklingml/"
``` 
So that we ignore the unrelated errors that are causing the failure in this PR and to allow for fixing them in a separate PR later.

**Comment by holdenk** [comment]
Awesome, mind if I cover this in the Friday livestream review?

**Comment by mohamed-ali** [comment]
@holdenk yes sure go ahead :)

**Review by holdenk — APPROVED** [review]
Awesome, thank you for fixing this. I've made a follow up issue ( https://github.com/sparklingpandas/sparklingml/issues/49 ) to track the current flake8 ignored errors.

**Pull request merged**
